fix(bug): fix TypeError in manual_tests.py
Fixed the following compiler error that was thrown when running
manual_tests.py:
TypeError: run() missing 1 required positional argument: 'filter'